#/****************************************************************************** 
#** Program Filename: makefile
#** Author: Hailey Wilder
#** Description: This is the makefile for lab4 
#*******************************************************************************/

CC=g++
SRCS = main.cpp recursions.hpp recursions.cpp

all: ${SRCS}
	${CC} ${CFLAGS} ${SRCS} -o lab5
clean:
	rm -rf *.o lab5