# Program Filename: makefile 
# Author: Hailey Wilder
# Description: makefile for Project 4

CC=g++
SRCS = main.cpp Creature.hpp Creature.cpp Medusa.hpp Medusa.cpp Dice.hpp Dice.cpp Barbarian.hpp Barbarian.cpp Vampire.hpp Vampire.cpp BlueMen.hpp BlueMen.cpp HarryPotter.hpp HarryPotter.cpp stack.hpp stack.cpp structure.hpp structure.cpp queue.hpp queue.cpp

all: ${SRCS}
	${CC} ${CFLAGS} ${SRCS} -o project4
clean:
	rm -rf *.o project4
