###########################
# ** Program: makefile
# ** Author: Hailey Wilder
# ** Date: 03/15/17
###########################

CC=g++
SRCS = main.cpp FibonacciR.hpp FibonacciR.cpp FibonacciNR.hpp FibonacciNR.cpp 
CFLAGS = -lrt

all: ${SRCS}
	${CC} ${CFLAGS} ${SRCS} -o lab10
clean:
	rm -rf *.o lab10
