####################################
# Author: Hailey Wilder
# Description: makefile for lab9
####################################

CC=g++
SRCS = main.cpp Dice.hpp Dice.cpp Queue.hpp Queue.cpp Stack.hpp Stack.cpp

all: ${SRCS}
	${CC} ${CFLAGS} ${SRCS} -o lab9
clean:
	rm -rf *.o lab9

